FROM golang:1.8-alpine

WORKDIR /go/src/github.com/gorobot-library/orca

RUN apk add --no-cache \
    gcc \
    git \
    glide \
    musl-dev \
    nano \
    openssl \
    make

RUN mkdir -p "$HOME/.orca"

COPY orca.example.toml $HOME/.orca/orca.toml

CMD [ "sh" ]
