# ----------------------------------------
# {{.Name}}
#
FROM {{"{{.Base}}"}}

RUN apk add --no-cache \
    ca-certificates \
 && apk add --no-cache --virtual .build-deps \
    curl \
    gcc \
    linux-headers \
    make \
    musl-dev \
    openssl \
 && curl -SLO "{{"{{.URL}}"}}" \
 && echo "{{"{{.Hash}}"}}" | sha256sum -c - \
 && mkdir -p "{{.Name}}" \
 && tar -xzf "{{"{{.File}}"}}" -C "{{.Name}}" --strip-components=1 \
 && rm "{{"{{.File}}"}}" \
 && cd "{{.Name}}" \
 && make -j$(getconf _NPROCESSORS_ONLN) \
 && make install \
 && rm -r "{{.Name}}" \
 && apk del .build-deps

{{if .HasEntrypoint -}}
COPY docker-entrypoint.sh /
ENTRYPOINT ["docker-entrypoint.sh"]
{{- end -}}

CMD [ "{{.Name}}" ]
